version: "3.7"

services:
  ssh:
    build:
      context: 7.5/
    environment:
      SSH_USER: john
      #SSH_USER_FILE: "/run/secrets/ssh_user"
      SSH_PASSWORD: doe
      #SSH_PASSWORD_FILE: "/run/secrets/ssh_password"
      #SSH_PUBLIC_KEY: "ssh bla"
      #SSH_PUBLIC_KEY_FILE: "/run/secrets/authorized_keys"
      SSH_HOME_DIR: "/var/www"
      SSH_CHOWN_HOME_DIR: "true"
      SSH_SHELL: "/bin/bash"
      SSH_USER_ID: 100
      SSH_GROUP_ID: 101
    ports:
      - "2222:22"
    volumes:
      - "./7.5/usr/local/bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./test/ssh_user:/run/secrets/ssh_user"
      - "./test/ssh_password:/run/secrets/ssh_password"
      - "./test/authorized_keys:/run/secrets/authorized_keys"
