version: "3.7"

services:
  ssh:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SSH_USER: john
      SSH_PASSWORD: doe
      SSH_ROOT_PUBLIC_KEY: "ssh-rsa abc test@example.com"
    ports:
      - "22:2222"
