version: "3.7"

services:
  ssh-7.5:
    image: servivum/ssh:7.5
    build:
      context: 7.5/
  ssh-7.5-common:
    image: servivum/ssh:7.5-common
    build:
      context: 7.5-common/
  ssh-7.5-php:
    image: servivum/ssh:7.5-php
    build:
      context: 7.5-php/
